== Overview

_Unlike the rest of the Agrest documentation that talks about the server framework, this document should be of interest
not only to the server-side developers, but to the client-side devs as well, as it demonstrates how to access Agrest
services._

"Agrest Protocol" is based on HTTP and JSON and defines how a client can communicate with Agrest endpoints. It consists
of two things:

* A format of _JSON documents_ used in requests and responses. It can work with any application-specific data model.
* A set of _control parameters_ for the client to request a specific representation of the model from the server (i.e.
the client can control sorting, filtering, offsets and included properties of the response objects). An endpoint may
support all or a subset of these parameters, depending on its intention and capabilities.

As we'll see below, the protocol defines some powerful features that give a lot of flexibility to the client to decide
what data is retrieved from the service and how it should look like. The fact that every Agrest service looks the same
regardless of a specific data model simplifies the implementation of the client. And the server implementation is
assisted by the framework.

=== Data Model

The examples in this document are using a simple "bookstore" model. Here it is defined as pseudocode:
```
Author
  - id : long
  - name : string
  - dateOfBirth : date
  - books : list<Book>
```

```
Book
  - id : long
  - title : string
  - genre: string
  - author : Author
```
As you see, the model consists of two entities (Author and Book), each with an "id" property, some value properties
(strings, dates, etc.) and related entity properties (`list<Book>`, `Author`). `id`, `attribute` and `relationship` are
the terms used throughout Agrest to distinguish between these types of properties.

