== JSON Documents

=== Message Response

This document is used in response to POST, PUT or DELETE when no entity data is returned to the client.

[source,json]
----
{
   "message" : "..."
}
----
.Message Response Document properties
[cols="1,15,~"]
|===
|`message`
|string
|An optional human-readable message, usually provided to explain reasons of a failure.
|===

=== Collection Response

This document is used in response to GET, POST or PUT to return data from the server. This is the format used to
return any kind of data to the client.

[source,json]
----
{
   "data" : [
      { "id" : 5, "name": "A" },
      { "id" : 8, "name": "B" }
   ],
   "total" : 2
}
----

.Collection Response Document properties
[cols="1,15,~"]
|===
|`data`
|list or object
|A list (or sometimes, an object) that contains entity objects. The schema of the objects is implicit, and depends on
the endpoint model and request <<Control Parameters, control parameters>>. Each object may contain other objects, with
an arbitrary number of nesting levels.
|`total`
|int
|The total number of objects in the collection. This is usually equal to the size of the `data` list. Except when
<<Pagination,pagination>> is in use, in which case the total corresponds to the size of the collection ignoring
pagination. I.e. it may be greater than the number of the returned objects in the "data" array.
|===

=== Update Request

This document is used as a body of a POST or PUT request to pass the data from the client to the server to modify an
entity collection. It is either a single object or a collection of objects (so pure custom model, no Agrest-specific
properties) :

[source,json]
----
{ "id" : 5, "name": "X" }
----

[source,json]
----
[
   { "id" : 5, "name": "X" },
   { "id" : 8, "name": "Y" }
]
----

NOTE: While collection response documents can contain object trees with an unlimited depth (entities with their related
entities, with their own related entities and so on), update documents can only have properties of a single entity.
It can still have references to the related entities as described below, but no entity nesting.

==== Updating To-One Relationships

To set a to-one relationship of an updated entity, use a pair "propertyName" : "related_id" in the update request document:

[source,json]
----
{ "id" : 5, "related": 10 }
----

==== Updating To-Many Relationships

To set a to-many relationship of an updated entity, pass a collection of ids for the relationship property in the
update request document:

[source,json]
----
{ "id" : 5, "related": [101, 2, 305] }
----
