== Control Parameters

Agrest protocol control parameters are `exp`, `sort`, `dir`, `start`, `limit`, `mapBy`, `include`, `exclude`. They are
passed as URL query parameters (e.g. `my?include=name`) with the goal to shape the <<Collection Response>> document.
With their help, the client can decide how to sort, filter, paginate the objects in the `data` collection, and which
object properties to include.

These parameters are applied to `GET` and often to `POST` and `PUT` requests (when those latter ones return
<<Collection Response>>).

Parameter values can be either simple strings/numbers or short JSON structures. JSON structures may require proper URL
encoding to be done by the client.

=== exp

`exp` is used to filter objects in the response collection. It can take one of the three forms, depending on the
parameter binding style:
[source]
----
exp=<exp_string> <1>
exp=["<exp_string>", "value1", "value2"] <2>
exp={"exp"="<exp_string>", "params":{ "param1" : "value1", "param2", "value2"}} <3>
----

<1> Without parameters, an expression it is just a string (we'll explain what `exp_string` is shortly)
<2> An expression with parameter resolution _by position_ is represented as a list, where the expression string is the first
element, and all subsequent elements are positional parameters
<3> An expression with parameter resolution _by name_ is represented as a map with "exp" and "params" properties

`exp_string` is a conditional expression based on Agrest own "expression DSL", that should be intuitively understood
by most programmers. Here are some examples:

[source]
----
name='Ernest Hemingway'
books.title = 'A Farewell to Arms'
title = not in ('A Farewell to Arms', 'For Whom the Bell Tolls')
title like 'A%' and author.dateOfBirth > $afterDate
----

_TODO: A more comprehensive Agrest exp format specification is forthcoming. Until then, please check
https://cayenne.apache.org/docs/4.2/cayenne-guide/expressions.html[Apache Cayenne expressions] that use practically
the same syntax (except Agrest would not allow "db:" expressions). And see the examples below_

A few things to note about the examples above:

* Expressions use dot-separated paths to refer to the values of object properties
* There is an implicit "root entity" to which the paths are applied. It is either the main entity of
the request or, when an expression is used inside an `include`, a related entity. So `name` and `books.title` would work
with `Author`, while `title` and `author.dateOfBirth` - with `Book`.
* Parameters always start with a "$" sign, regardless whether they are resolved by name or by position

Here are a few examples using an expression key (not showing URL encoding):

Example 1: Filtering on a single property:
[source]
----
exp=name='Ernest Hemingway'
exp=name like 'E%'
exp=name likeIgnoreCase '%ab%'
----

Example 2: Filtering on a relationship with outer join (the "+" sign is notation for "outer"). Comparing to null returns
all authors who have no books in the system:

[source]
----
exp=books+ = null
----

Example 3: Parameter resolution by position:

[source]
----
exp=["author.dateOfBirth > $afterDate","1900-01-01"]
----

Example 4: Parameter resolution by name:

[source]
----
exp={"exp":"author.dateOfBirth > $afterDate", "params":{"afterDate":"1900-01-01" }}
----

=== sort / dir

`sort` and `dir` are used to order objects in the response collection. The following forms are supported:

[source]
----
sort=<prop_path> <1>
sort=<prop_path>&dir=<dir_spec> <2>
sort=<json_sort_object> <3>
sort=[<json_sort_object>,...] <4>
----

<1> Ascending sort by a single property
<2> Sort by a single property with explicit direction
<3> Sort by a single property with a sort object
<4> Sort by multiple properties with a list of sort objects

`dir` is added to specify sort direction when sorting is done on a single property. It can have one of these values:

* `ASC`: this is also the default, when no `dir` is provided
* `DESC`
* `ASC_CI`: for case-insensitive ascending ordering
* `DESC_CI`: for case-insensitive descending ordering

`<json_sort_object>` allows to specify both the property and the direction in one place and has a form of
`{"property": .., "direction": .. }`. `direction` is optional and takes the same values as `dir`. Let's demonstrate
all the flavors with a few examples:

Example 1: Ascending sort by a single property:

[source]
----
sort=name
----

Example 2: Descending sort by a single property with explicit direction:

[source]
----
sort=id&dir=DESC
----

Example 3: Descending sort by a single property with a sort object:

[source]
----
sort={"property":"id","direction":"DESC"}
----

Example 4: Sort by multiple properties with a list of sort objects:

[source]
----
`sort=[{"property":"name"},{"property":"dateOfBirth","direction":"DESC"}]`
----

[#Pagination]
=== start / limit

`start` and `limit` parameters are used for client-controlled pagination of a response collection. They can be used
together or individually to request a range of objects in a collection.

`start` is an offset within the "data" array. All the objects below this offset are discarded from the response
collection. Default `start` is 0.

`limit` is a maximum number of objects in the collection "data". Default is no limit.

`limit` is applied after `start`. So for a collection of 10 objects, `?start=2&limit=5` would result in objects 2
through 6 returned from the server. Returned Collection "total" would still be 10.

=== mapBy

`mapBy` parameter is used to reshape the `data` collection from a list of objects to a map of lists, keyed by some
property. E.g. consider a typical list response:

[source,json]
----
{
"data" : [
    { "id" : 8, "title" : "One Hundred Years of Solitude",  "genre" : "fiction" },
    { "id" : 5, "title" : "Battle Cry of Freedom",  "genre" : "history" },
    { "id" : 12, "title" : "For Whom the Bell Tolls",  "genre" : "fiction" }
  ],
  "total":3
}
----

Using `mapBy=genre` it can be transformed to a map. The total here is still the number of all objects in all the maps
combined:

[source,json]
----
{
"data" : {
    "fiction" : [
        { "id" : 8, "title" : "One Hundred Years of Solitude",  "genre" : "fiction" },
        { "id" : 12, "title" : "For Whom the Bell Tolls",  "genre" : "fiction" }
    ],
    "history" : [
        { "id" : 5, "title" : "Battle Cry of Freedom",  "genre" : "history" }
    ]
  },
  "total" : 3
}
----

=== include / exclude

`include` and `exclude` are used to recursively shape individual objects in a response collection. These are the
controls that turn your REST endpoints from fixed models to _graphs_ that can be dynamically navigated by the clients.

`exclude` format:
[source]
----
// a single property path
exclude=<prop_path>

// a JSON array of property paths
exclude=[<prop_path>,...]
----

`include` format:
[source]
----
// a single property path
include=<prop_path>

// a JSON include object
include=<json_include_object>

// a JSON array of property paths and include objects
include=[<prop_path_or_json_include_object>,...]
----

`<json_include_object>` has the following format:

[source]
----
{
    "path": .. , // the only required property
    "exp": .. ,
    "sort": .. ,
    "start": ..,
    "limit": ..
    "mapBy": ..
    "include": ...
}
----

The only required property is `path` that determines which property is included. If the `path` points to a relationship,
the object can contain properties corresponding to all the individual controls we've seen already (even a nested `include`!).
Those controls are applied to the related entity denoted by the `path`.

A few more notes before we show the examples:

* What is included by default? As we've discussed above, Agrest model entities consist of id, attribute and relationship
properties. If no includes are specified, <<Collection Response>> document would contain the id and all the attributes
of a given entity, and none of the relationships.
* Multiple `include` and `exclude` parameters can be used in a single request. They will be combined together.

Now let's see the examples:

NOTE: In the examples below we will omit the `{"data":[..],"total":N}` collection document wrapper, and will only
show the structure of an individual object within the "data" collection.

Example 1: Include the id and the attributes, but exclude the "genre" attribute:

[source]
----
exclude=genre
----

[source,json]
----
{ "id" : 8, "title" : "One Hundred Years of Solitude" }
----

Example 2: Only include "id":

[source]
----
include=id
----

[source,json]
----
{ "id" : 8 }
----

Example 3: Multiple includes, one of them pointing to the attributes of a related entity:

[source]
----
include=id&include=author.name
----

[source,json]
----
{ "id" : 8, "author" : {"name" : "Gabriel García Márquez"} }
----

Example 4: JSON include object with sorting, filtering and a nested include:

[source]
----
include={"path":"books","exp":"title like '%a%'","sort":"title", "include":"title"}
----

[source,json]
----
{
   "books" : [
      { "title" : "Autumn of the Patriarch" },
      { "title" : "One Hundred Years of Solitude" }
   ]
}
----

Example 5: JSON include object with mapBy and a nested include:

[source]
----
include={"path":"books","mapBy":"genre", "include":"id"}
----

[source,json]
----
{
   "books" : {
      "fiction" : [
        { "id" : 55 },
        { "id" : 8 }
      ]
   }
}
----

Example 6: Include and Exclude parameters can take an array of values:

[source]
----
include=["id","name"]
----

[source,json]
----
{ "id" : 45, "name" : "Gabriel García Márquez"}
----

Example 7: The include array can contain a combination of paths and include objects:

[source]
----
include=["id","books.title",{"path":"books","exp":"title like %a%'"}]
----

[source,json]
----
{
   "id" : 45,
   "books" : [
      { "title" : "Autumn of the Patriarch" },
      { "title" : "One Hundred Years of Solitude" }
   ]
}
----

Example 8: Include array is recursive. Attributes of a related entity can be specified as a JSON array. Also, there is a
shortcut - instead of `{"path":"books","include":[..]}}`, we are using `{"books":[..]}` :


[source]
----
include=["id",{"books":["id", "title"]}]
----

[source,json]
----
{
   "id" : 45,
   "books" : [
      { "id" : 55, "title" : "Autumn of the Patriarch" },
      { "id" : 8, "title" : "One Hundred Years of Solitude" }
   ]
}
----


