== Control Parameters

Agrest protocol control parameters are `exp`, `sort`, `dir`, `start`, `limit`, `mapBy`, `include`, `exclude`. They are
passed as URL query parameters (e.g. `my?include=name`) with the goal to shape the <<Collection Response>> document.
With their help, the client can decide how to sort, filter, paginate the objects in the `data` collection, and which
object properties to include.

These parameters are applied to `GET` and often to `POST` and `PUT` requests (when those latter ones return
<<Collection Response>>).

Parameter values can be either simple strings/numbers or short JSON structures. JSON structures may require proper URL
encoding to be done by the client.

=== exp

`exp` is used to filter objects in the response collection. It can take one of the three forms, depending on the
parameter binding style:
[source]
----
exp=<exp_string> <1>
exp=["<exp_string>", "value1", "value2"] <2>
exp={"exp"="<exp_string>", "params":{ "param1" : "value1", "param2", "value2"}} <3>
----

<1> Without parameters, an expression it is just a string (we'll explain what `exp_string` is shortly)
<2> An expression with parameter resolution _by position_ is represented as a list, where the expression string is the first
element, and all subsequent elements are positional parameters
<3> An expression with parameter resolution _by name_ is represented as a map with "exp" and "params" properties

`exp_string` is a conditional expression based on Agrest own "expression DSL", that should be intuitively understood
by most programmers. Here are some examples:

[source]
----
name='Ernest Hemingway'
books.title = 'A Farewell to Arms'
title = not in ('A Farewell to Arms', 'For Whom the Bell Tolls')
title like 'A%' and author.dateOfBirth > $afterDate
----

_TODO: A more comprehensive Agrest exp format specification is forthcoming. Until then, please check
https://cayenne.apache.org/docs/4.2/cayenne-guide/expressions.html[Apache Cayenne expressions] that use practically
the same syntax (except Agrest would not allow "db:" expressions). And see the examples below_

A few things to note about the examples above:

* Expressions use dot-separated paths to refer to the values of object properties
* There is an implicit "root entity" to which the paths are applied. It is either the main entity of
the request or, when an expression is used inside an `include`, a related entity. So `name` and `books.title` would work
with `Author`, while `title` and `author.dateOfBirth` - with `Book`.
* Parameters always start with a "$" sign, regardless whether they are resolved by name or by position

Here are a few complete examples:

Example 1: Filtering on a single property:
[source]
----
exp=name='Ernest Hemingway'
----

Example 2: Filtering on a relationship with outer join (the "+" sign is notation for "outer"). Comparing to null returns
all authors who have no books in the system:

[source]
----
exp=books+ = null
----

Example 3: Parameter resolution by position:

[source]
----
exp=["author.dateOfBirth > $afterDate","1900-01-01"]
----

Example 4: Parameter resolution by name:

[source]
----
exp={"exp":"author.dateOfBirth > $afterDate", "params":{"afterDate":"1900-01-01" }}
----

=== sort / dir

`sort` and `dir` parameters are used to order objects in the response collection.

Example 1: Sort on a single property.

`sort=vhost`

Example 2: Sort descending on a property.

`sort=id&amp;dir=DESC`

`dir` can be one of `ASC` (default), `DESC`, `ASC_CI` (for case-insensitive asending ordering), `DESC_CI` (for case-insensitive descending ordering)

Example 3: Same as 2, but sort is a JSON object.

`sort={"property":"vhost","direction":"DESC"}`

`direction` takes the same values as `dir` above - `ASC` (implied default), `DESC`, `ASC_CI`, `DESC_CI`

Example 4: Multiple sortings as a single JSON structure.

`sort=[{"property":"name"},"property":"vhost","direction":"DESC"}]`


[#Pagination]
=== start / limit

`start` and `limit` parameters are used to implement client-controlled pagination of the response collection.
They are used together or separately to request a range of objects in a bigger collection.

`start` is an offset within the "data" array. All the objects below this offset are discarded from the collection.
Default `start` is 0.

`limit` is a maximum number of objects in the collection "data". Default is no limit.

`limit` is applied after `start`. So for a collection with a total of 10 objects,
`?start=2&amp;limit=5` would result in objects 2 through 6 returned from the server. Returned Collection "total" would still be 10.


=== mapBy

`mapBy` parameter is used to reshape the `data` collection from a list of objects to a map of lists, keyed by some
property. E.g. consider a typical list response:

[source,json]
----
{
"data" : [
    { "title" : "Agrest mapBy",  "body" : "mapBy is used ..", "publishedOn" : "6 July, 2018" },
    { "title" : "Other Tech News",  "body" : "Java community ..", "publishedOn" : "8 October, 2017" },
    { "title" : "Introducing Agrest",  "body" : "Agrest is a ..", "publishedOn" : "6 July, 2018" }
  ],
  "total":3
}
----

Using `mapBy` it can be transformed to a map:

`mapBy=publishedOn`

[source,json]
----
{
"data" : {
    "8 October, 2017" : [
        { "title" : "Other Tech News",  "body" : "Java community …", "publishedOn" : "8 October, 2017" }
    ],
    "6 July, 2018" : [
        { "title" : "Agrest mapBy",  "body" : "mapBy is used …", "publishedOn" : "6 July, 2018" },
        { "title" : "Introducing Agrest",  "body" : "Agrest is a …", "publishedOn" : "6 July, 2018" }
    ]
  },
  "total" : 3
}
----

=== include / exclude

`include` and `exclude` parameters are used to recursively shape individual objects in the response collection. Model
entities may have "simple" properties (attributes) and properties that point to
related entities (relationships). By default, Collection Document contains entity
representation that includes its "id", all of its attributes, and none of the
relationships. "include" and "exclude" parameters allow the client to request a specific
subset of entity properties, including related entities. Some examples are given below,
showing include/exclude parameters and resulting entity contents.

Example 1: Include default properties (all entity attributes) minus "vhost" attribute.

`exclude=vhost`

[source,json]
----
{ "id" : 45, "name" : "Agrest Site" }
----

Example 2: Exclude all properties, but "id".

`include=id`

[source,json]
----
{ "id" : 45 }
----

Example 3: Multiple includes, one of them points to attributes of related entity.

`include=id&amp;include=articles.title`

[source,json]
----
{
   "id" : 45,
   "articles" : [
      { "title" : "Agrest Includes" },
      { "title" : "Other Tech News" },
      { "title" : "Introducing Agrest" }
   ]
}
----

Example 4: Advanced include. Include specification can itself be a JSON object and
contain `"exp"`, `"sort"`, `"start"` and `"limit"` keys shaping up a collection
of related objects for each root object.

`include={"path":"articles","exp":"title like '%Agrest%'","sort":"title"}&amp;include=articles.title`

[source,json]
----
{
   "id" : 45,
   "articles" : [
      { "title" : "Introducing Agrest" },
      { "title" : "Agrest Includes" }
   ]
}
----

Example 5: Related objects as a map. Here we'll map article bodies by title.

`include={"path":"articles","mapBy":"title"}&amp;include=articles.body`

[source,json]
----
{
   "articles" : {
      "Introducing Agrest" : { "body" : "Agrest is a .." },
      "Agrest Includes" : { "body" : "Includes are .." }
   }
}
----

Example 6: Include and Exclude parameters have ability to take an array of values:

`include=["id","name"]`

[source,json]
----
{ "id" : 45, "name" : "Agrest Site" }
----

Example 7: The array can contain both the simple include and the advanced include values

`include=["id","articles.title",{"path":"articles","exp":"title like '%Agrest%'"}]`

[source,json]
----
{
   "id" : 45,
   "articles" : [
      { "title" : "Introducing Agrest" },
      { "title" : "Agrest Includes" }
   ]
}
----

Example 8: Attributes of a related entity can be presented as an inner array in JSON format:

`include=["id","name",{"articles":["title","body"]}]`

[source,json]
----
{
   "id" : 45,
   "name" : "Agrest Site",
   "articles" : [
      { "title" : "Introducing Agrest", "body" : "Agrest is a .." },
      { "title" : "Agrest Includes", "body" : "Includes are .." }
   ]
}
----

Example 9: The related entity can be specified as a path value:

`include=["id","name",{"articles.categories":["id","name"]}]`

Example 10: The advanced include can contain the array of include values:

`include={"path":"articles","sort":"title","include":["title",{"categories":["id","name"]}]}`

