== Expression Syntax

Expressions passed via `exp` control parameter or inside the JSON `include` are conditions evaluated in the context of
the root request entity (in the former case), or a nested entity (in the latter case). We've already discussed
the URL parameter structure for `exp` (e.g. how to pass parameters). Here we will focus on the syntax of the expression itself.

=== Path Expressions

An important building block of expressions is a property path. It is a dot-separated String of property names
implicitly rooted in some entity:

[source]
----
// Entity id. Most Agrest entities have the property called "id"
id

// Entity attribute name (a "simple" or "value" property)
dateOfBirth

// Entity relationship name
books

// Dot-separated paths that span multiple entities
books.id
books.library.name

// Adding "+" to a relationship would indicate "left join" semantics
// for the backend resolving the path
books+.library.name
----

=== Scalars

Another type of expression components is "scalars" or value "literals". There are three types of scalars - booleans,
numbers and strings. Booleans are just true or false, in upper or lower case:
[source]
----
true
TRUE
false
FALSE
----

A variety of number formats are supported - positive / negative, whole / decimal:
[source]
----
// positive int
1

// negative int
-2

// long
3147483647L

// double
2.1

// big decimal
2.1001234065B
----

Strings are included in single or double quotes:

NOTE: Unquoted strings are generally treated as property paths

[source]
----
'abc'
"abc"

// if quotes are present in strings, either use non-conflicting quote symbols,
// or escape the quotes
'a"c'
"a'c"
"a\"c"
----

Agrest backend framework would also recognize Strings representing date / time components in ISO 8601 format,
and can convert them to the proper types based on the expression context. From the expressions perspective
those are just Strings:
[source]
----
"2023-09-11"
"2023-09-11T00:00:01"
----

=== Named Parameters

TODO ...

=== Arithmetic Expressions
[source]
----
a + 5
1 - a
a * b
b.c / d
----

=== Bitwise Expressions

TODO ...

=== Functions
Agrest supports a number of scalar functions. Functions can take zero or more arguments. Paths, scalars, arithmetic
and bitwise expressions can be function arguments were appropriate. Supported functions:
[source]
----
// date/time
currentDate()
currentTime()
currentTimestamp()
day(exp)
dayOfMonth(exp)
dayOfWeek(exp)
dayOfYear(exp)
hour(exp)
minute(exp)
month(exp)
second(exp)
week(exp)
year(exp)

// numeric
abs(exp)
mod(exp1, exp2)
sqrt(exp)

// string
concat(exp1, exp2)
length(exp)
locate(toLocateExp, inStringExp [, startAtIndexExp])
lower(exp)
substring(strExp, startIndexExp [, lenExp])
trim(exp)
upper(exp)
----

=== Simple Conditions

TODO ...

=== Chained Conditions

TODO ...