== Expression Syntax

Expressions passed via an `exp` control parameter or inside a JSON `include` are conditions evaluated in the context of
the root request entity (in the former case), or a nested entity (in the latter case). We've already discussed
the URL parameter structure for `exp` (e.g. how to pass parameters). Here we will focus on the syntax of the expression
itself.

NOTE: The expression syntax presented here is a part of the Agrest protocol. Some Agrest backends may not be able to
support every single expression described here, but most should work with a reasonable subset. And the default Java
server shipped with Agrest (that works on top of relational databases) supports the syntax in its entirety.

=== Literals

There are a few kinds of literals that denote various constant scalar values in expressions - numbers, strings, dates, etc.

Null is a literal that indicates an absent value:
[source]
----
null
----

Boolean literals are either true or false:
[source]
----
true
false
----

A variety of number literals are supported - positive / negative, whole / decimal, etc.:
[source]
----
// positive int
1

// negative int
-2

// long
3147483647L

// double
2.1

// big decimal
2.1001234065B

// TODO: hex types, etc.
----

String literals contain arbitrary sequences of characters, and are enclosed in either single or double quotes:

[source]
----
'abc'
"abc"

// if quotes are present in strings, either use non-conflicting quote symbols,
// or escape them explicitly
'a"c'
"a'c"
"a\"c"
----

Date / time components are regular quoted strings that follow ISO 8601 format:
[source]
----
"2023-09-11"
"2023-09-11T00:00:01"
----

=== Paths

Important building blocks of expressions are property paths. They are dot-separated unquoted strings that point to
property names of some entity:

[source]
----
// Entity id. Most Agrest entities have it
id

// Entity attribute (a "simple" or "value" property)
dateOfBirth

// Entity relationship
books

// Dot-separated path spanning multiple entities
books.id
books.library.name

// Adding "+" to a relationship name anywhere in the path indicates "optional" semantics.
// This is a hint to the server evaluating the expression. E.g. if the expression is
// translated to SQL, LEFT JOIN will be used for optional expressions
books+.library.name
----

NOTE: Paths are used not only in expressions, but also in a variety of other control parameters (`sort`, `include`,
`exclude`, `mapBy`)

=== Parameters

Parameters are placeholders in expressions that are replaced with scalar values when the expression is
evaluated on the server. Parameters are unquoted strings that start with a dollar sign:

```
// must start with a dollar sign,
// followed by a sequence of letters, digits or underscores
$myVar
$1
$_myVar
```

As described in the previous chapter, parameters can be resolved either by name (the name is the part of the string
that follows the dollar sign), or by position in the expression. Parameter naming syntax for both styles is the
same (e.g. there's no special significance to using a number as the param name, like `$15`. It is simply a parameter
called "15").

=== Arithmetic Expressions
[source]
----
a + 5
1 - a
a * b
b.c / d
----

=== Bitwise Expressions

TODO ...

=== Functions
Agrest supports a number of scalar functions. Function names are case-sensitive. Functions can take zero or more
arguments that can be paths, scalars, arithmetic and bitwise expressions. Supported functions:
[source]
----
// date/time
currentDate()
currentTime()
currentTimestamp()
day(exp)
dayOfMonth(exp)
dayOfWeek(exp)
dayOfYear(exp)
hour(exp)
minute(exp)
month(exp)
second(exp)
week(exp)
year(exp)

// numeric
abs(exp)
mod(exp1, exp2)
sqrt(exp)

// string
concat(exp1, exp2)
length(exp)
locate(toLocateExp, inStringExp [, startAtIndexExp])
lower(exp)
substring(strExp, startIndexExp [, lenExp])
trim(exp)
upper(exp)
----

=== Simple Conditions
"Simple" conditional expressions are built from paths and literals and a variety of comparison operators:

[source]
----
name = 'Joe'
name != 'Alice'
name <> 'Alice'

salary < 50000
salary <= 50000
age > 16
age >= 21

salary between 50000 and 150000
salary not between 50000 and 150000

color in ('blue', 'red', 'green')
color not in ('blue', 'red', 'green')
----

A special kind of comparison is SQL-style pattern matching with "like" operator: `a like '<pattern>'`. In the pattern
string, a few characters have special meanings as "wildcards": "%" stands for any sequence of characters, while "\_"
stands for any single character. If you want "%" or "_" to be treated as a regular character, not a wildcard, you
should prefix it with an arbitrary escape character, as shown in the examples below.

[source]
----
name like 'A%'
name like 'A_C_'

// do not treat the first underscore as a wildcard
name like 'Ax_C_' escape 'x'

// case-insensitive matching
name likeIgnoreCase 'a%'

// not like
name not like 'A%'
name not likeIgnoreCase 'A%'
----

=== Chained Conditions

TODO ...