== Overview

=== What is Agrest Server Framework

Agrest provides a server framework to quickly build Java RESTful applications that
serve and consume data graphs in a way compatible with the Agrest Protocol.

The core API of the framework is not dependent on a specific REST engine (such as Jersey
or Spring Web), and can be integrated with most of them. The same is true for
data backends - a number of them can be plugged in, either provided by Agrest (Apache Cayenne ORM)
or implemented by the user. The simplest form of a custom backend is a Java function performing
some calculation to produce a value for a single property.

Agrest server is model-driven with its own metadata layer. It allows to take some existing
data model (e.g. POJOs, ORM entities, etc.), and shape it in the form appropriate for the REST API
you intend to build. Agrest entity model also allows defining per-entity,
and per-request security policies at the object and attribute level.

Agrest integrates with Swagger to API serve documentation in the widely-adopted https://swagger.io/specification/[OpenAPI 3]
format.

==== REST Engines

Out of the box Agrest supports the following Java REST engines:

* https://en.wikipedia.org/wiki/Jakarta_RESTful_Web_Services[JAX-RS - Jakarta]
* Older JavaEE version of JAX-RS

NOTE: It should be fairly straightforward to port Agrest to other engines like SpringWeb.

==== Data Sources

Out of the box Agrest supports the following data sources:

* https://cayenne.apache.org/[Apache Cayenne], which is a well-optimized ORM backend with support for
all Agrest Protocol features. Currently, supported version of Cayenne is 4.2.
* Custom functions (derived attribute calculation, REST services mapping, etc.)



NOTE: We are working on alternative advanced query-based data backends, specifically JPA. As of this writing
it is experimental, and we'd recommend Cayenne as the most tried and reliable.

=== Java Version

Java 11 or newer is required.


