== Runtime

`AgRuntime` object is the core of Agrest. It provides the strategies to process various types of requests, stores
the app data "schema", and serves as an integration point for various data backends. When working in the
environments like <<Jersey Integration,Jersey / JAX-RS>>, you may not be interacting with `AgRuntime` directly, but it
is still the object doing all the heavy lifting under the hood. And you will still need to assemble the runtime
before you can use Agrest.

This is how you create a bare-bone default runtime:

[source,java,indent=0]
----
include::../../../main/java/io/agrest/docs/framework/AgRuntimeExample.java[tag=create]
----
Usually you would add at least one backend provider though (such as
<<Cayenne Integration,Apache Cayenne>>), and often - your own extensions. Internally `AgRuntime` uses a lightweight
dependency-injection container to assemble its services, and can be extended using "modules":

[source,java,indent=0]
----
include::../../../main/java/io/agrest/docs/framework/AgRuntimeExample.java[tag=create-with-converter]
----
<1> Registering a module with support for a custom value type of `Money`, providing a converter for it to be read from
JSON. `b` is a special `Binder` object that allows to define or override services in the DI environment.

NOTE: To see what kinds of services and extensions are available and how to use the Binder API, you may
check the source code of `io.agrest.runtime.AgCoreModule` on GitHub. This is the main module of Agrest, and defines the
default behavior for the framework.

=== Auto-Loadable Modules

More complex Agrest extensions may be packaged in their own `.jar` files. Agrest has a mechanism to automatically detect
such jars on the classpath, load and merge them into the runtime. To turn your code into an auto-loadable module, add a
file called `META-INF/services/io.agrest.AgModuleProvider` to the classpath of your project (usually under
`src/main/resources`), with a single line that is a fully-qualified class name of the `AgModuleProvider` implementor.
E.g. the same extension as above can be rewritten to be auto-loadable:

.META-INF/services/io.agrest.AgModuleProvider
[source]
----
com.foo.MyModuleProvider
----
[source,java,indent=0]
----
include::../../../main/java/io/agrest/docs/framework/MyModuleProvider.java[tag=all]
----
[source,java,indent=0]
----
include::../../../main/java/io/agrest/docs/framework/MyModule.java[tag=all]
----

NOTE: You may not be writing auto-loadable modules that often for "normal" applications, as it is much easier to create
inline modules. But this is a useful mechanism for creating reusable Agrest extensions.


