== Jersey Integration

Jersey is often used to run Agrest applications. It supports Java API for RESTful services (JAX-RS).
Agrest works with either the legacy Jersey 2 (`agrest-jaxrs2` module) or the Jakarta-based Jersey 3 (`agrest-jaxrs3` module).
Their main difference is JAX-RS package names (`javax.` vs `jakarta.`). We will provide Jersey 3 examples below, but
they should equally apply to Jersey 2, and for the most part work with other JAX-RS servers.

Jersey doesn't run standalone until at least version 3.1, and requires some kind of Java "server", such as Jetty,
Spring Boot, Bootique, etc. Examples of server integrations are provided in the links below:

* https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest3x/index.html[Jersey 3 own docs]
* link:../getting-started/[Spring Boot 2.x Agrest tutorial] (Jersey 2 only)
* https://github.com/bootique/bootique-jersey[Bootique Jersey], or even better -
https://github.com/bootique/bootique-agrest[Bootique Agrest]

For the rest of this document we will focus on Agrest usage in the Jersey environment, ignoring the underlying server.

NOTE: SpringBoot: SpringBoot 2.x supports Jersey 2, while SpringBoot 3.x will support Jersey 3

NOTE: Bootique Note: Bootique 2.x supports Jersey 2, while Bootique 3.x supports both Jersey 2 and 3

=== Dependencies

You may or may not need to explicitly import Jersey dependencies, depending on how you are planning to run it (see
above). But you will need the following Agrest import:

[source,xml,indent=0]
----
include::../../../../pom.xml[tag=agrest-jaxrs3]
----

=== Jersey Bootstrap

Jersey provides a convenience superclass called `ResourceConfig` that you can subclass and bootstrap your application
in the constructor:

[source,java,indent=0]
----
include::../../../main/java/io/agrest/docs/framework/AgrestJerseyApp.java[tag=all]
----
<1> The app class extending Jersey `ResourceConfig`
<2> Create Agrest runtime, as described in the <<Runtime>> section
<3> Register Agrest runtime with Jersey / JAX-RS environment
<4> Register your app API endpoints with Jersey (we will see these endpoint classes shortly)

=== Custom Extensions

TODO: JAX-RS extensions via `AgFeatureProvider`

=== Agrest  Endpoints

Below is a typical JAX-RS endpoint that invokes Agrest. We'll talk more about request processing in the following
chapters. Here we'll just show how to access Agrest runtime from within JAX-RS:

[source,java,indent=0]
----
include::../../../main/java/io/agrest/docs/framework/AuthorApi.java[tag=all]
----
<1> JAX-RS `Configuration` is injected using JAX-RS `@Context` annotation
<2> `AgJaxrs` is a helper that locates the `AgRuntime` within `Configuration` and starts a request-specific Agrest
processor

NOTE: Agrest tries to stay maximally non-invasive. You can mix Agrest endpoints with non-Agrest endpoints, and even
within the endpoint you can execute any custom code.