== GET Requests

With just a few lines of code, Agrest can process `GET` requests conforming to
link:../protocol#control-parameters[Agrest protocol]. Here is how you may program a request handler:

[source,java,indent=0]
----
include::../../../main/java/io/agrest/docs/framework/GET_AuthorApi.java[tag=get_all_params]
----

<1> Start "select" operation builder
<2> Pass all request parameters from JAX-RS `UriInfo` object. The framework will process those that are defined in the
Agrest protocol (`exp`, `include`, etc.) and ignore the rest
<3> Execute the select operation

=== GET a Single Object

Often a REST API would only return a single object matching a given `id`. Here is how this can be implemented in Agrest:

[source,java,indent=0]
----
include::../../../main/java/io/agrest/docs/framework/GET_AuthorApi.java[tag=get_by_id]
----

<1> "id" may be modeled as a part of the URL path and injected via JAX-RS `@PathParam`
<2> Here is how the "id" is passed to the Agrest operation builder
<3> Instead of `get()`, call `getOne()` to execute the operation. It still returns the same `DataResponse`, but
will handle cases when there is no matching object found (`404` response status code instead of `200`) and also when
more than one object is found (this will result in `500` status code).

=== GET Object Children

Another common pattern in a REST API design is hierarchical resource URLs used to retrieve "children" of a given
"parent" object. E.g. the books of a single known author:

[source,java,indent=0]
----
include::../../../main/java/io/agrest/docs/framework/GET_AuthorApi.java[tag=get_for_author]
----

<1> Define a URL path with author ID and relationship name
<2> Capture author ID as a `@PathParam`
<3> Set the "parent" object of the request

NOTE: "Parent" API is just syntactic sugar to support hierarchical resource URLs like `/author/576/books`. Similar
functionality can also be implemented as `/book?exp=author=576` or `/author/576?include=books`.

=== Explicit Protocol Parameters
Not every endpoint has to support every single protocol parameter. Depending on the application needs (and backend
capabilities), you may explicitly define which parameters are supported:

[source,java,indent=0]
----
include::../../../main/java/io/agrest/docs/framework/GET_AuthorApi.java[tag=get_include_sort]
----

<1> Instead of `UriInfo`, capture individual query parameters using `@QueryParam` annotation
<2> Build a `AgRequest` object with all the passed parameters
<3> Pass the `AgRequest` to the operation builder

=== Server-Side Protocol Parameters

The `AgRequest` object has another useful property. Unlike `UriInfo` that captures everything that was passed in the
URL by the client, it is manually constructed *on the server*. So you can amend the request object in your application
code to limit what the client can do or to define the default data appearance:

[source,java,indent=0]
----
include::../../../main/java/io/agrest/docs/framework/GET_AuthorApi.java[tag=get_server_side_rules]
----

<1> Pass an expression limiting the dataset. The client will not be able to override this filter, and can only narrow
the dataset further by using the URL `exp` parameter (see the next item)
<2> Combine the server-side expression with a client expression that came from the URL
<3> Define data ordering (and do not allow the client to change it)

=== Customizing Entities

As already mentioned in the chapter on <<Entity Overlays,Entity Overlays>>, you can redefine the shape of entities,
their retrieval strategies and access rules via per-request overlays:

[source,java,indent=0]
----
include::../../../main/java/io/agrest/docs/framework/GET_AuthorApi.java[tag=get_with_overlay]
----

<1> Hide an attribute using an overlay if the request user is not an administrator
<2> Apply the overlay to the request

NOTE: While the request is for the `Author` entity, overlays can be for any entity at all (including the `Author`). In our
case the overlay is for the `Book`, meaning that it will be applied if the user runs a request like `/author?include=books`

=== Property Visibility

There's a more direct API to implement per-request property visibility rules. It can also be applied to any entity in
the request graph, not just the root entity:

[source,java,indent=0]
----
include::../../../main/java/io/agrest/docs/framework/GET_AuthorApi.java[tag=get_with_prop_filter]
----

<1> Apply "property filter" for non-admin users to the Book entity, hiding "copiesSold" property from the response objects

Internally property filter is implemented as an overlay, similar to the previous example, but from the user perspective
the filter API is less verbose.

NOTE: Don't forget that you can also define readability rules for individual properties globally using `@AgAttribute`
annotation (see <<Schema Annotations>>)

=== Object Visibility

The previous examples shows how you can hide certain _properties_ based on per-request custom logic. Similarly,
you can exclude certain _objects_ from the response with custom "read filters":

[source,java,indent=0]
----
include::../../../main/java/io/agrest/docs/framework/GET_AuthorApi.java[tag=get_with_read_filter]
----

<1> If only modern authors are requested, apply a "read filter" to exclude older authors. The filter lambda must
return "true" for the objects that pass the check and should be included in the response.

NOTE: If custom object filtering rules can be written as an `Exp` on the root entity, consider doing that instead of
using a read filter. It would move the filtering logic to the data store and out of your code, potentially
optimizing the processing. You can refer to an example above from the <<Server-Side Protocol Parameters>> chapter.


