:agrest-header: _chapters/header.html

= Getting Started

Through this tutorial we will be building a simple Bookstore REST application using Agrest and a relational database.
Agrest can work with various Java REST API stacks and backends. So there are some choices to make for the
purpose of the tutorial. So we decided to use the following components:

* SpringBoot / Jersey
* Derby database
* Apache Cayenne ORM backend

We'll be using Maven and Java 17 to build and run the project. If you prefer Gradle, it should work as well of course.

_The full code of the tutorial is available
https://github.com/agrestio/agrest-docs/tree/5.x/agrest-docs-get-started-cayenne-sb[on Github]._

include::_chapters/_01_project_setup.adoc[]
include::_chapters/_02_cayenne_mapping.adoc[]
include::_chapters/_03_endpoints.adoc[]
include::_chapters/_04_custom_property.adoc[]
include::_chapters/_05_openapi_docs.adoc[]

== Conclusion

This concludes our tutorial. From here you should check the link:../protocol["Protocol" document] on how to interact
with Agrest from the client, and the link:../framework["Server Framework" document] for an in-depth discussion of how
to write model-driven endpoints with user-specific schemas, security controls, a variety of backends, etc.
