:agrest-header: _chapters/header.html

= Getting Started

Through this tutorial we will be building a simple Bookstore REST application using Agrest with a real database.
Agrest can work with various REST API stacks, and different backends. The tutorial will be done with the following
components:

* SpringBoot / Jersey (via `spring-boot-starter-jersey`)
* Derby database
* Apache Cayenne ORM backend

To build the project, we'll be using Maven and Java 17. But keep in mind that Agrest would work fine with Gradle and
supports Java versions 11 and higher.

_The tutorial document will focus on the important pieces to understand how to write an Agrest application. The full
code is available https://github.com/agrestio/agrest-docs/tree/5.x/agrest-docs-get-started-cayenne-sb[on Github]._

include::_chapters/_01_project_setup.adoc[]
include::_chapters/_02_cayenne_mapping.adoc[]
include::_chapters/_03_endpoints.adoc[]

== Conclusion

This concludes our tutorial. From here you should check the "Protocol" document on how to interact with Agrest from
the client, and the "Server Framework" documentation for an in-depth discussion of how to write model-driven endpoints
with user-specific schemas, security controls, a variety of backends, etc.