== Writing REST Endpoints

=== Creating data with POST

Let's write a couple of POST endpoints to allow users to create Authors and Books. We'll start by creating Java classes
`AuthorApi` and `BookApi`, placing a few JAX-RS annotations on them, and injecting JAX-RS `Configuration` object:

[source,java,indent=0]
----
include::../../../main/java/io/agrest/tutorial/sb/api/AuthorApi.java[tag=base]
----

[source,java,indent=0]
----
include::../../../main/java/io/agrest/tutorial/sb/api/BookApi.java[tag=base]
----

Now let's create POST methods in both classes. In `AuthorApi`:
[source,java,indent=0]
----
include::../../../main/java/io/agrest/tutorial/sb/api/AuthorApi.java[tag=post]
----
<1> Start a builder for "create" operation. `config` parameter passed to `create(..)`, contains Agrest runtime
<2> Pass URL parameters. This will control the shape of the response
<3> Execute create operation and return created Author to the client

In `BookApi`
[source,java,indent=0]
----
include::../../../main/java/io/agrest/tutorial/sb/api/BookApi.java[tag=post]
----
Notice the difference between Author and Book POST methods. In the former case, after creating an object
Agrest returns `DataResponse<Author>`, allowing the client to inspect the result of the operation (e.g. obtain the
Author's ID generated by the server). In the latter case, it returns `SimpleResponse` that does not contain any data.

=== Setting up the App

Now that we have the basic endpoint, how do we integrate them in our app?


